name: DEB Release

on:
  push:
    tags:
      - 'DEB*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build solver_application
        run: |
          cd solver_application
          cmake -DDEB=ON -B ./_build
          cd _build
          make package
          make package_source
      - name: Pre_Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ver-${{ github.sha }}
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
      - name: Release
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: solver_application/_build/Solver.deb
          asset_name: Solver.deb
          asset_content_type: application/deb
